### ISSUE TITLE
`FileNotFoundError` for `cover.jpg`

### ISSUE THREAD

**Issue by Slyyxp** [Slyyxp/rsack#25]
```py
Traceback (most recent call last):
  File "C:\Users\Cheek\AppData\Local\Programs\Python\Python39\Scripts\rsack-script.py", line 33, in <module>
    sys.exit(load_entry_point('rsack==0.1.4', 'console_scripts', 'rsack')())
  File "C:\Users\Cheek\AppData\Local\Programs\Python\Python39\lib\site-packages\rsack-0.1.4-py3.9.egg\rsack\main.py", line 25, in main    
  File "C:\Users\Cheek\AppData\Local\Programs\Python\Python39\lib\site-packages\rsack-0.1.4-py3.9.egg\rsack\bugs.py", line 36, in __init__
  File "C:\Users\Cheek\AppData\Local\Programs\Python\Python39\lib\site-packages\rsack-0.1.4-py3.9.egg\rsack\bugs.py", line 69, in _album
  File "C:\Users\Cheek\AppData\Local\Programs\Python\Python39\lib\site-packages\rsack-0.1.4-py3.9.egg\rsack\bugs.py", line 124, in _download_cover
FileNotFoundError: [Errno 2] No such file or directory: 'Z:\\Music\\Korean\\TREASURE(트레저)\\TREASURE(트레저) - THE SECOND STEP _ CHAPTER ONE \\cover.jpg'
```

**Comment by Slyyxp** [comment]
1b3e04299affd100795a9e114f1f7e41bd0f7668
