### ISSUE TITLE
bugs error in latest version 

### ISSUE THREAD

**Issue by aespapa** [Slyyxp/rsack#76]
C:\Users\honeysaerom\Desktop\rsack-master>rsack -u "https://music.bugs.co.kr/album/4082713?wl_ref=M_contents_01_04"
2022-12-29 21:17:23.736 | INFO     | rsack.clients.bugs:auth:29 - Login Successful : 모바일 무제한 듣기(매월)
2022-12-29 21:17:23.751 | INFO     | rsack.bugs:__init__:25 - Threads: 2
2022-12-29 21:17:23.798 | INFO     | rsack.bugs:_album:60 - Album: 해요해요
2022-12-29 21:17:23.814 | ERROR    | rsack.bugs:_album:65 - An error has been caught in function '_album', process 'MainProcess' (9416), thread 'MainThread' (2656):
Traceback (most recent call last):

  File "C:\Users\honeysaerom\AppData\Local\Programs\Python\Python311\Scripts\rsack-script.py", line 33, in <module>
    sys.exit(load_entry_point('rsack==0.7.25', 'console_scripts', 'rsack')())
    │   │    └ <function importlib_load_entry_point at 0x000001CB532F0720>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "C:\Users\honeysaerom\AppData\Local\Programs\Python\Python311\Lib\site-packages\rsack-0.7.25-py3.11.egg\rsack\main.py", line 27, in main
  File "C:\Users\honeysaerom\AppData\Local\Programs\Python\Python311\Lib\site-packages\rsack-0.7.25-py3.11.egg\rsack\bugs.py", line 29, in __init__
> File "C:\Users\honeysaerom\AppData\Local\Programs\Python\Python311\Lib\site-packages\rsack-0.7.25-py3.11.egg\rsack\bugs.py", line 65, in _album
  File "C:\Users\honeysaerom\AppData\Local\Programs\Python\Python311\Lib\site-packages\rsack-0.7.25-py3.11.egg\rsack\bugs.py", line 80, in _album_path

KeyError: 'append_date'
Traceback (most recent call last):
  File "C:\Users\honeysaerom\AppData\Local\Programs\Python\Python311\Scripts\rsack-script.py", line 33, in <module>
    sys.exit(load_entry_point('rsack==0.7.25', 'console_scripts', 'rsack')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\honeysaerom\AppData\Local\Programs\Python\Python311\Lib\site-packages\rsack-0.7.25-py3.11.egg\rsack\main.py", line 27, in main
  File "C:\Users\honeysaerom\AppData\Local\Programs\Python\Python311\Lib\site-packages\rsack-0.7.25-py3.11.egg\rsack\bugs.py", line 29, in __init__
  File "C:\Users\honeysaerom\AppData\Local\Programs\Python\Python311\Lib\site-packages\rsack-0.7.25-py3.11.egg\rsack\bugs.py", line 66, in _album
  File "C:\Users\honeysaerom\AppData\Local\Programs\Python\Python311\Lib\site-packages\rsack-0.7.25-py3.11.egg\rsack\bugs.py", line 209, in _download_cover
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\honeysaerom\\Desktop\\mp3\\수진(Sujin)\\수진(Sujin) - 해요해요\\cover.jpg'

**Comment by Slyyxp** [comment]
I'm unable to replicate this, works as expected on my end.

Can you provide the **[Bugs]** section of your configuration?
**WITHOUT** leaking your username and password.

**Comment by aespapa** [comment]
> I'm unable to replicate this, works as expected on my end.
> 
> Can you provide the **[Bugs]** section of your configuration? **WITHOUT** leaking your username and password.

it means rsack_settings?

**Comment by aespapa** [comment]
> > I'm unable to replicate this, works as expected on my end.
> > Can you provide the **[Bugs]** section of your configuration? **WITHOUT** leaking your username and password.
> 
> it means rsack_settings.ini?

[Bugs]

threads = 2
path = C:\Users\honeysaerom\Desktop\mp3
artist_folders = Y
lyrics = T
contributions = N
cover_size = original

[Genie]

threads = 2
path = C:\Users\honeysaerom\Desktop\mp3
artist_folders = Y
timed_lyrics = Y
contributions = N

[KKBox]
email = email@protonmail.com
password = mypassword
threads = 2
path = C:\Music\KKBox

genie work well. bugs doesn't work.

**Comment by Slyyxp** [comment]
Configuration and album pathing is overhauled in latest release, you can re-open if persists.

**Comment by aespapa** [comment]
> Configuration and album pathing is overhauled in latest release, you can re-open if persists.

did you get available 
https://music.bugs.co.kr/album/178427?wl_ref=list_ab_03_ab 
this one?

**Comment by aespapa** [comment]
> Configuration and album pathing is overhauled in latest release, you can re-open if persists.

https://music.bugs.co.kr/album/4871?wl_ref=list_ab_01_likeab
did you available this one?

**Comment by Slyyxp** [comment]
Caused by 'Label' mising within Bugs metadata response.
I have removed the Label and Agency templates, this should now work with latest version.
