### ISSUE TITLE
error log in

### ISSUE THREAD

**Issue by evafans** [Slyyxp/rsack#80]
**2023-01-18 12:04:55.925 | CRITICAL | rsack.clients.kkbox:login:93 - Credentials invalid
2023-01-18 12:04:55.927 | INFO     | rsack.clients.kkbox:login:101 - Logged in
2023-01-18 12:04:56.642 | CRITICAL | rsack.clients.kkbox:get_album:137 - Album not found
2023-01-18 12:04:56.644 | DEBUG    | rsack.clients.kkbox:get_date:54 - Scraping release date
2023-01-18 12:04:58.018 | ERROR    | rsack.kkbox:__init__:23 - An error has been caught in function '__init__', process 'MainProcess' (4172), thread 'MainThread' (9388):
Traceback (most recent call last):

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Scripts\rsack-script.py", line 33, in <module>
    sys.exit(load_entry_point('rsack==0.7.6', 'console_scripts', 'rsack')())
    │   │    └ <function importlib_load_entry_point at 0x0000022ED2270720>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\rsack-0.7.6-py3.11.egg\rsack\main.py", line 42, in main
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\rsack-0.7.6-py3.11.egg\rsack\kkbox.py", line 23, in __init__
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\rsack-0.7.6-py3.11.egg\rsack\kkbox.py", line 95, in _download_album

TypeError: 'NoneType' object does not support item assignment**

my account is working, is there anything I missed?

**Comment by reini267** [comment]
> Double check:
> 
> * The credentials are CORRECT

Where do our credentials go? Do I just type my un/pswd on the rsack_settings.ini files, then install rsack again?

**Comment by Slyyxp** [comment]
https://github.com/Slyyxp/rsack/wiki/Configuration

Check the example configuration.

**Comment by reini267** [comment]
> https://github.com/Slyyxp/rsack/wiki/Configuration
> 
> Check the example configuration.

So I made a KKBox account and entered my credentials as indicated in the example configuration into rsack_settings.ini, but I'm getting the same error as @evafans. Am I missing something or is the issue with the account itself?

**Comment by Slyyxp** [comment]
Generally I receive invalid credentials 1 week before the Trial Account expires so I suggest if you're within that range to just make a new fresh account.

Otherwise if this is happening on a fresh account I am not sure what the issue would be. I am able to download on a fresh trial account in hong kong region at the time of writing this.

**Comment by Yuq-q** [comment]
I did encounter this problem before, I am not sure if it is because of the problem here, but when I delete "region_bypass=True" or set it to "False", the account can log in normally
https://github.com/Slyyxp/rsack/pull/79/commits/decde5bd8d03d510d70d17a3e776229a15392f7f

**Comment by evafans** [comment]
> I did encounter this problem on Jan 15 , I am not sure if it is because of the problem here(#79 --- [decde5b](https://github.com/Slyyxp/rsack/commit/decde5bd8d03d510d70d17a3e776229a15392f7f)), but when I delete "region_bypass=True" or set it to "False", the account can log in normally

It doesnt work for me
