### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jisamcom** [Slyyxp/rsack#83]
python version : 3.11.1 
pip version : 22.3.1 
os : win 11 

installed rsack using pip.

E:\FLAC Processing\BugsPy>rsack
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python311\Scripts\rsack.exe\__main__.py", line 4, in <module>
  File "C:\Program Files\Python311\Lib\site-packages\rsack\main.py", line 6, in <module>
    from rsack import bugs, genie, kkbox
  File "C:\Program Files\Python311\Lib\site-packages\rsack\kkbox.py", line 7, in <module>
    from rsack.clients.kkbox import KkboxAPI
  File "C:\Program Files\Python311\Lib\site-packages\rsack\clients\kkbox.py", line 6, in <module>
    from Cryptodome.Cipher import ARC4
ModuleNotFoundError: No module named 'Cryptodome'

**Comment by Slyyxp** [comment]
#81
