### ISSUE TITLE
error msg -> mutagen.flac.error: block is too long to write

### ISSUE THREAD

**Issue by honeykkk** [Slyyxp/rsack#91]
ERROR    | rsack.bugs:_download:164 - An error has been caught in function '_download', process 'MainProcess' (2172), thread 'ThreadPoolExecutor-0_1' (4512):
Traceback (most recent call last):

https://music.bugs.co.kr/album/20144731?wl_ref=list_ab_01_ab

**Comment by Slyyxp** [comment]
It's probably your album artwork settings.
Only 3 lines from the traceback is not helpful.

**Comment by honeykkk** [comment]
fully traceback here.

-----------------

2023-07-09 11:00:25.356 | DEBUG    | rsack.bugs:_tag:235 - Writing tags to C:\Users\---------\Desktop\music downloads\---------\--------- - ---------\12. ---------.flac
2023-07-09 11:00:25.362 | ERROR    | rsack.bugs:_download:164 - An error has been caught in function '_download', process 'MainProcess' (11036), thread 'ThreadPoolExecutor-0_0' (7280):
Traceback (most recent call last):

  File "C:\Users\---------\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 995, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002C4ECF73C40>
    └ <Thread(ThreadPoolExecutor-0_0, started 7280)>
  File "C:\Users\---------\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x000002C4ECF73920>
    └ <Thread(ThreadPoolExecutor-0_0, started 7280)>
  File "C:\Users\---------\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(ThreadPoolExecutor-0_0, started 7280)>
    │    │        │    └ (<weakref at 0x000002C4F03F0630; to 'ThreadPoolExecutor' at 0x000002C4EEC08F10>, <_queue.SimpleQueue object at 0x000002C4F03C...
    │    │        └ <Thread(ThreadPoolExecutor-0_0, started 7280)>
    │    └ <function _worker at 0x000002C4EF68D120>
    └ <Thread(ThreadPoolExecutor-0_0, started 7280)>
  File "C:\Users\---------\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
    │         └ <function _WorkItem.run at 0x000002C4EF755BC0>
    └ <concurrent.futures.thread._WorkItem object at 0x000002C4F03EA790>
  File "C:\Users\---------\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <concurrent.futures.thread._WorkItem object at 0x000002C4F03EA790>
             │    │   │    └ ({'track_id': 30934044, 'disc_id': 1, 'track_no': 12, 'track_title': '---------', 'title_yn': 'N', 'len': '03:...
             │    │   └ <concurrent.futures.thread._WorkItem object at 0x000002C4F03EA790>
             │    └ <bound method Download._download of <rsack.bugs.Download object at 0x000002C4F02079D0>>
             └ <concurrent.futures.thread._WorkItem object at 0x000002C4F03EA790>
> File "C:\Users\---------\AppData\Local\Programs\Python\Python311\Lib\site-packages\rsack\bugs.py", line 164, in _download
    self._tag(track, c_path)
    │    │    │      └ 'C:\\Users\\---------\\Desktop\\music downloads\\---------\\--------- - The Perfect Red Velvet - The 2nd Al...
    │    │    └ {'track_id': 30934044, 'disc_id': 1, 'track_no': 12, 'track_title': '---------', 'title_yn': 'N', 'len': '03:4...
    │    └ <function Download._tag at 0x000002C4EF782F20>
    └ <rsack.bugs.Download object at 0x000002C4F02079D0>
  File "C:\Users\---------\AppData\Local\Programs\Python\Python311\Lib\site-packages\rsack\bugs.py", line 238, in _tag
    f_file.save()
    │      └ <function FLAC.save at 0x000002C4EF755580>
    └ {'discnumber': ['1'], 'tracktotal': ['12'], 'disctotal': ['1'], 'comment': ['30934044'], 'title': ['---------'...
  File "C:\Users\---------\AppData\Local\Programs\Python\Python311\Lib\site-packages\mutagen-1.45.1-py3.11.egg\mutagen\_util.py", line 185, in wrapper
    return func(*args, **kwargs)
           │     │       └ {}
           │     └ ({'discnumber': ['1'], 'tracktotal': ['12'], 'disctotal': ['1'], 'comment': ['30934044'], 'title': ['---------...
           └ <function FLAC.save at 0x000002C4EF7556C0>
  File "C:\Users\---------\AppData\Local\Programs\Python\Python311\Lib\site-packages\mutagen-1.45.1-py3.11.egg\mutagen\_util.py", line 156, in wrapper
    return func(self, h, *args, **kwargs)
           │    │     │   │       └ {}
           │    │     │   └ ()
           │    │     └ FileThing(fileobj=<_io.BufferedRandom name='C:\\Users\\---------\\Desktop\\music downloads\\---------\\Red Velvet (...
           │    └ {'discnumber': ['1'], 'tracktotal': ['12'], 'disctotal': ['1'], 'comment': ['30934044'], 'title': ['---------'...
           └ <function FLAC.save at 0x000002C4EF755620>
  File "C:\Users\---------\AppData\Local\Programs\Python\Python311\Lib\site-packages\mutagen-1.45.1-py3.11.egg\mutagen\flac.py", line 848, in save
    self._save(filething, self.metadata_blocks, deleteid3, padding)
    │    │     │          │    │                │          └ None
    │    │     │          │    │                └ False
    │    │     │          │    └ [<mutagen.flac.StreamInfo object at 0x000002C4F03BD690>, <SeekTable seekpoints=[(0, 0, 1152), (440064, 829252, 1152), (881280...
    │    │     │          └ {'discnumber': ['1'], 'tracktotal': ['12'], 'disctotal': ['1'], 'comment': ['30934044'], 'title': ['---------'...
    │    │     └ FileThing(fileobj=<_io.BufferedRandom name='C:\\Users\\---------\\Desktop\\music downloads\\---------\\Red Velvet (...
    │    └ <function FLAC._save at 0x000002C4EF755440>
    └ {'discnumber': ['1'], 'tracktotal': ['12'], 'disctotal': ['1'], 'comment': ['30934044'], 'title': ['---------'...
  File "C:\Users\---------\AppData\Local\Programs\Python\Python311\Lib\site-packages\mutagen-1.45.1-py3.11.egg\mutagen\flac.py", line 864, in _save
    data = MetadataBlock._writeblocks(
           │             └ <classmethod(<function MetadataBlock._writeblocks at 0x000002C4EF74F060>)>
           └ <class 'mutagen.flac.MetadataBlock'>
  File "C:\Users\---------\AppData\Local\Programs\Python\Python311\Lib\site-packages\mutagen-1.45.1-py3.11.egg\mutagen\flac.py", line 154, in _writeblocks
    data += cls._writeblock(block)
    │       │   │           └ <Picture '' (17002709 bytes)>
    │       │   └ <classmethod(<function MetadataBlock._writeblock at 0x000002C4EF74EFC0>)>
    │       └ <class 'mutagen.flac.MetadataBlock'>
    └ bytearray(b'\x00\x00\x00"\x04\x80\x04\x80\x00\x00\x0e\x00\x11\xc1\n\xc4B\xf0\x00\x94s\x0c6^\xa40T\x86\xa0#w\xe0=\xc1\xb7v\xa8...
  File "C:\Users\---------\AppData\Local\Programs\Python\Python311\Lib\site-packages\mutagen-1.45.1-py3.11.egg\mutagen\flac.py", line 137, in _writeblock
    raise error("block is too long to write")
          └ <class 'mutagen.flac.error'>

mutagen.flac.error: block is too long to write

**Comment by Slyyxp** [comment]
It's caused due to the album artwork being too large to write to the file.

**Comment by honeytheyeon** [comment]
Then, what format should I change the album size?

**Comment by honeykkk** [comment]
Then, what format should I change the album size?
now set to original.
