### ISSUE TITLE
KeyError: 'proxy'

### ISSUE THREAD

**Issue by gerberanub** [Slyyxp/rsack#94]
root@webtop:/config/Downloads/rsack# rsack -u https://music.bugs.co.kr/album/20563467
Traceback (most recent call last):
  File "/usr/local/bin/rsack", line 33, in <module>
    sys.exit(load_entry_point('rsack==0.7.9', 'console_scripts', 'rsack')())
  File "/usr/local/lib/python3.10/dist-packages/rsack-0.7.9-py3.10.egg/rsack/main.py", line 27, in main
  File "/usr/local/lib/python3.10/dist-packages/rsack-0.7.9-py3.10.egg/rsack/bugs.py", line 23, in __init__
KeyError: 'proxy'

what am i missing ?
please help me

**Comment by Slyyxp** [comment]
Proxy should be set to 'false' instead of 'socks5://username:password@ip:port'. 
My fault for not having this as default instead of providing an example.
