### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by gerberanub** [Slyyxp/rsack#97]
PS C:\Users\lee_e> rsack -u https://music.bugs.co.kr/artist/80246375
2024-04-16 20:58:49.509 | INFO     | rsack.clients.bugs:auth:44 - Login Successful : Premium 무제한 듣기(30일)
2024-04-16 20:58:49.512 | INFO     | rsack.bugs:__init__:25 - Threads: 2
2024-04-16 20:58:50.496 | INFO     | rsack.bugs:_artist:42 - 66 releases found
2024-04-16 20:58:50.498 | DEBUG    | rsack.bugs:_artist:49 - Skipping album contribution
2024-04-16 20:58:50.517 | INFO     | rsack.bugs:_album:60 - Album: 초대형 노래방 서바이벌 VS SEMI FINAL
2024-04-16 20:58:50.553 | DEBUG    | rsack.bugs:_album_path:94 - Creating F:/rsack/YoungK/Young K (DAY6), 로이킴, 기리보이, 김민석, 임한별, 소유 (SOYOU), 박재정, 서은광 (비투비), 카더가든, 장우영, 김영석, 박종민, 위재연, 임정현, 홍승민, 김 창운, 정성보, 조곤, 박한담, 우디(Woody)/Young K (DAY6), 로이킴, 기리보이, 김민석, 임한별, 소유 (SOYOU), 박재정, 서은광 (비투비), 카더가든, 장우영, 김영석, 박종민, 위재연, 임정현, 홍승민, 김창운, 정성보, 조곤, 박한담, 우디(Woody) - 초대형 노래방 서바이벌 VS SEMI FINAL
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\lee_e\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\Scripts\rsack.exe\__main__.py", line 7, in <module>
  File "C:\Users\lee_e\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\rsack\main.py", line 29, in main
    bugs.Download(type="artist", id=int(id))
  File "C:\Users\lee_e\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\rsack\bugs.py", line 27, in __init__
    self._artist(id)
  File "C:\Users\lee_e\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\rsack\bugs.py", line 51, in _artist
    self._album(album['album_id'])
  File "C:\Users\lee_e\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\rsack\bugs.py", line 66, in _album
    self._download_cover()
  File "C:\Users\lee_e\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\rsack\bugs.py", line 210, in _download_cover
    with open(self.cover_path, 'wb') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'F:/rsack/YoungK/Young K (DAY6), 로이킴, 기리보이, 김민석, 임한 별, 소유 (SOYOU), 박재정, 서은광 (비투비), 카더가든, 장우영, 김영석, 박종민, 위재연, 임정현, 홍승민, 김창운, 정성보, 조 곤, 박한담, 우디(Woody)/Young K (DAY6), 로이킴, 기리보이, 김민석, 임한별, 소유 (SOYOU), 박재정, 서은광 (비투비), 카더가 든, 장우영, 김영석, 박종민, 위재연, 임정현, 홍승민, 김창운, 정성보, 조곤, 박한담, 우디(Woody) - 초대형 노래방 서바이벌 VS SEMI FINAL\\cover.jpg'

there is folder created "Young K (DAY6), 로이킴, 기리보이, 김민석, 임한별, 소유 (SOYOU), 박재정, 서은광 (비투비), 카더가든, 장우영, 김영석, 박종민, 위재연, 임정현, 홍승민, 김창운, 정성보, 조곤, 박한담, 우디(Woody)"  
i guess the folder name is too long ... so it couldn't download

**Comment by Slyyxp** [comment]
There is code to handle this, or so I thought. Will take a look at it when given time.
